version: "3.8"
services:
  node:
    container_name: frontend
    hostname: fContainer
    build: .
    volumes:
      - $HOME/.ssh:/root/.ssh
      - $HOME/.gitconfig:/root/.gitconfig
      - /workspace/node_modules
      