name: Next.js CI/CD

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - name: Checking for .DS_Store files 👮
        uses: Maxelweb/ds-store-patrol@v1

      - name: Checkout 🛎
        uses: actions/checkout@v2

      - name: Setup node env 🏗
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: yarn

      - name: Install dependencies 👨🏻‍💻
        run: yarn install

      - name: Run linter 👀
        run: yarn lint

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          repository: 'ryoheinan/e-shoku'
