name: Pull Request Manager

on:
  pull_request:
    types: [opened, unassigned]
  workflow_dispatch:

jobs:
  assign:
    runs-on: ubuntu-20.04
    timeout-minutes: 1

    steps:
      - run: gh pr edit $NUMBER --add-assignee $ASSIGNEE
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.pull_request.number }}
          ASSIGNEE: ${{ github.event.pull_request.user.login }}
        if: ${{ toJSON(github.event.pull_request.assignees) == '[]' }}
